import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import TestRunner from '@/components/TestRunner'
import SimpleTest from '@/lib/tests/simple'
import ErrorTest from '@/lib/tests/error'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>next-worker E2E Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.heading}>
          next-worker E2E Testing
        </div>
        <div className={styles.subheading}>
          - Developed by @sudoshreyansh
        </div>
        <div className={styles.tests}>
          <TestRunner component={SimpleTest} title={<div><b>useWorker():</b> Add an array of numbers</div>} />
          <TestRunner component={ErrorTest} title={<div><b>useWorker():</b> Throw error</div>} />
        </div>
      </main>
    </>
  )
}
